#!/bin/bash
glibtoolize --force
aclocal -I /usr/local/share/aclocal -I m4
autoheader
automake --add-missing --copy
autoconf

export LD_TWOLEVEL_NAMESPACE=1
./configure prefix=/usr/local --disable-static-daq
